### ISSUE TITLE
[1.5pt] Delete a Billionaire

### ISSUE THREAD

**Issue by rachidelaid** [rachidelaid/billionaire-appointment-back-end#10]
Here you are expected to add the following:

- Front-end
    - Only admins should have access to this
    - This page should fetch and display all billionaires with a delete button on them.
    - When the delete button is clicked you should send a request to the backend with the id of the billionaire to be deleted
    - Write tests for your page
- Back-end
    - Implement ability to ensure that those without the admin role cannot delete a billionaire
    - Implement a route for this functionality
    - Implement a controller action to receive the billionaire id as params and destroy the model
    - Return a corresponding json response
        - billionaire deleted successfully
        - Could not delete the billionaire, ensure to add the obj.errors as a property in the json response
    - Write tests for your controller (request specs)
    - Write tests for your api

**Comment by orozCoding** [comment]
**Back-end PR:**
https://github.com/rachidelaid/billionaire-appointment-back-end/pull/21

**Front-end PR:**
https://github.com/rachidelaid/billionaire-appointment-front-end/pull/6
