### ISSUE TITLE
[1.5pt] Navigation Panel

### ISSUE THREAD

**Issue by rachidelaid** [rachidelaid/billionaire-appointment-back-end#15]
Here you are expected to achieve the following:
- Side navigation menu
    - Should have links to every part of the application
        - Billionaires Links
        - Reserve Billionaire link
        - My Reservations Link
        - Add Billionaire Link - Should only be seen by admins
        - Delete a Billionaire link - Should only be seen by admins
    - It should also have the application logo
    - Logout button should also be visible
    - Social media icons and copyright date
    - It should have ability to slide in from the left in the reserve Billionaire page
    - Active links should show the active colour and other links when hovered on should show the accent colour
    - It should be open by default on all other pages except the home page
    - Ensure that mobile navigation is also implemented to display on smaller screens
    - Write tests for your front-end

**Comment by guerreiropedr0** [comment]
This issue is in review [here](https://github.com/rachidelaid/billionaire-appointment-front-end/pull/10).
