### ISSUE TITLE
[1pt] Setup a new react application

### ISSUE THREAD

**Issue by rachidelaid** [rachidelaid/billionaire-appointment-back-end#4]
Here we are expected to achieve the following

    Install linters
    Install all libraries (Redux, Redux-thunk, React-router, React-Redux, Normal Css)
    Install Styling
    Install ESlint
    Create a redux store
    Install react-testing-library
    Install JEST
    Setup basic color combinations
    Setup Fonts
    Setup Redux actions / reducers
    Setup the Redux thunk file

**Comment by orozCoding** [comment]
**Pull request created in the front-end:**

https://github.com/rachidelaid/billionaire-appointment-front-end/pull/1
